Fix mini cart rendering error when order form isn't fetched
vtex-apps/minicart pull request #11
Opened 2018-05-14 15:01 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Fix mini cart rendering error when order form isn't fetched.

#### What problem is this solving?

#### How should this be manually tested?
https://minicart--storecomponents.myvtex.com/

#### Screenshots or example usage

#### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-05-14 16:44 UTC, salesfelipe approved these changes

2018-05-14 17:36 UTC, claudivanfilho requested changes

2018-05-14 17:36 UTC, ClaudivanFilho commented on CHANGELOG.md
> +- Fix minicart render errro when cannot fetch the orderForm from graphql.
errro

2018-05-14 17:37 UTC, andreldsa approved these changes

2018-05-14 17:38 UTC, claudivanfilho approved these changes

2018-05-15 14:14 UTC, brunojdo approved these changes

2018-05-15 14:14 UTC, merged