Add behavior tests in the minecart
vtex-apps/minicart pull request #118
Opened 2019-03-13 21:11 UTC by JuanAlmeida12

#### What is the purpose of this pull request?

-Add behavior tests in the minecart

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2019-03-13 21:25 UTC, klzns requested changes

2019-03-13 21:25 UTC, klzns commented on CHANGELOG.md
> +- Behavior tests.
Since this change will not publish a new version. This shouldn't be in the changelog. It's just implementation details.

2019-03-14 15:55 UTC, klzns approved these changes

2019-03-14 16:54 UTC, GustavoMA approved these changes
Rebase

2019-03-15 13:59 UTC, GustavoMA commented on react/package.json
> +    "@vtex/test-tools": "^0.1.2",
Update to `^0.1.3`

2019-03-15 14:12 UTC, merged