Update the propTypes to reuse the Mini cart's one
vtex-apps/minicart pull request #13
Opened 2018-05-22 20:38 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Update the propTypes to reuse the mini cart's one.

#### What problem is this solving?
This component was showing lots of warnings in the console because there were some incompatibilities with the propTypes.

#### How should this be manually tested?
(Access the workspace)[https://waza--storecomponents.myvtex.com/]

#### Screenshots or example usage

#### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-05-22 20:44 UTC, salesfelipe requested changes

2018-05-22 20:44 UTC, salesfelipe commented on react/MiniCartContent.js
>      /* Label to appear when the minicart is empty */
Label that will appear...

2018-05-22 20:44 UTC, salesfelipe commented on react/MiniCartContent.js
>      /* Label to appear in the finish shopping button */
idem

2018-05-22 20:44 UTC, salesfelipe commented on react/MiniCartContent.js
> +    /* Function to be called when a item is removed */
when an item

2018-05-22 20:47 UTC, claudivanfilho approved these changes

2018-05-23 12:32 UTC, lucasecdb requested changes

2018-05-23 12:32 UTC, lucasecdb commented on CHANGELOG.md
> +- Change PropTypes to reuse the mini cart's one.
No need to place `Change...` in the beginning, just describe what was changed.

2018-05-23 12:47 UTC, vitoriaHeliane commented on react/MiniCartContent.js
>      /* Label to appear when the minicart is empty */
DOne!

2018-05-23 12:47 UTC, vitoriaHeliane commented on react/MiniCartContent.js
>      /* Label to appear in the finish shopping button */
Done!

2018-05-23 12:47 UTC, vitoriaHeliane commented on react/MiniCartContent.js
> +    /* Function to be called when a item is removed */
Done!

2018-05-23 12:59 UTC, lucasecdb approved these changes
I think the alias prop types you define (such as `MiniCartPropTypes.labelMiniCartEmpty`) are unnecessary, and you should only define ones that are a complex type (e.g. `MiniCartPropTypes.data`), but it's something to discuss later.

2018-05-23 13:00 UTC, salesfelipe approved these changes

2018-05-23 13:05 UTC, brunojdo approved these changes

2018-05-23 13:05 UTC, brunojdo commented on react/MiniCartPropTypes.js
>    /* Show the remove item button or not */
Set the visibility of remove button

2018-05-23 13:05 UTC, brunojdo commented on react/MiniCartContent.js
> +    labelMiniCartEmpty: MiniCartPropTypes.labelMiniCartEmpty,
What's new put at the beginning of propTypes

2018-05-23 13:05 UTC, brunojdo commented on react/MiniCartContent.js
> +    labelMiniCartEmpty: MiniCartPropTypes.labelMiniCartEmpty,
Add a comment /* Reused props */

2018-05-23 13:08 UTC, vitoriaHeliane commented on react/MiniCartPropTypes.js
>    /* Show the remove item button or not */
Done!

2018-05-24 17:23 UTC, merged