Add SSR into mini cart content
vtex-apps/minicart pull request #16
Opened 2018-06-12 20:44 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Add SSR into mini cart content.

#### What problem is this solving?
This component didn't have SSR.

#### How should this be manually tested?
https://waza2--storecomponents.myvtex.com/

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-06-12 21:28 UTC, brunojdo requested changes

2018-06-12 21:28 UTC, brunojdo commented on react/components/MiniCartContent.js
> +    const labelEmpty = labelMiniCartEmpty || intl.formatMessage({ id: 'minicart-empty' })
Don't make sense put a spinner to be onSSR.

2018-06-13 17:12 UTC, vitoriaHeliane commented
It isn't necessary because the mini cart content is rendered just when the page is loaded.

2018-06-13 17:12 UTC, vitoriaHeliane commented
It isn't necessary because the mini cart content is rendered just when the page is loaded.

2018-06-13 17:12 UTC, closed without merging