use usequery and useMutation hooks
vtex-apps/minicart pull request #182
Opened 2019-10-23 21:37 UTC by jgfidelis

#### What is the purpose of this pull request?
use react-apollo@hooks

#### What problem is this solving?

#### How should this be manually tested?

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2019-10-24 12:34 UTC, lucasecdb commented on react/index.js
> +  const { loading, data={}} = useQuery(orderFormQuery, {ssr:false})
are you running prettier on these files?

2019-10-24 12:34 UTC, lucasecdb commented on react/index.js
> +  compose,
do you need this?

2019-10-24 12:35 UTC, lucasecdb commented
@jgfidelis can you provide a workspace with this changes linked?

2019-10-24 20:14 UTC, jgfidelis commented on react/index.js
> +  compose,
yes

2019-10-25 17:17 UTC, lucasecdb requested changes
please remove the commented code

2019-10-25 17:55 UTC, lucasecdb approved these changes
LGTM

2019-10-31 15:00 UTC, klzns approved these changes

2019-10-31 15:00 UTC, klzns commented on react/index.js
>      // eslint-disable-next-line react-hooks/exhaustive-deps
Why does it have that comment? Do you know? What happens if we remove it?

2020-04-28 18:23 UTC, Klynger commented
Going to close this PR due to inactivity

2020-04-28 18:23 UTC, closed without merging