Use the navigate function in order to benefit from apollo cache
vtex-apps/minicart pull request #198
Opened 2020-01-02 19:02 UTC by jeffersontuc

#### What is the purpose of this pull request?

As the title says, this PR adapts the minicart to use `render-runtime`'s navigate function.

#### What problem is this solving?

The checkout's cart now can benefit from the apollo cache.

#### How should this be manually tested?

- Open this [workspace](https://jeffaddepum--checkoutio.myvtex.com/)
- Add an item to cart
- Click on the cart icon at top right
- Proceed to cart
- Verify that the loading skeleton didn't appear

Alternatively, you can

- Add an item to cart
- Click on the cart icon at top right
- Open console dev tools
- Proceed to cart
- Verify that a request to get the `orderForm` is not being made

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-01-02 19:29 UTC, omninando approved these changes

2020-01-02 19:41 UTC, marcoskwkm requested changes
Add the case when the button redirects to the current Checkout to your test plan.

2020-01-02 19:41 UTC, marcoskwkm commented on react/BaseContent.tsx
> +  }
Navigation seems to be broken if the new checkout is not installed. I believe you should not use `navigate` in this case.

2020-01-02 21:57 UTC, marcoskwkm submitted a review, later dismissed

2020-01-02 21:57 UTC, marcoskwkm commented on react/BaseContent.tsx
> +    }
You should also take into account the case where `finishShoppingButtonLink` is truthy and the account has the new Cart installed. In this case, I believe you should not use `navigate` either. In short, you should only use `navigate` if it sends the user to the new Cart.

2020-01-02 22:43 UTC, marcoskwkm reviewed
LGTM, but just to be extra safe I'll approve this after you merge the changes in `checkout-resources`.

2020-01-02 22:43 UTC, marcoskwkm commented on react/BaseContent.tsx
> +    if (major && url === checkoutUrl) {
nit: I would make it explicit that we want `major > 0` instead of just a truthy value.

2020-01-06 17:29 UTC, victorhmp approved these changes

2020-01-29 17:58 UTC, omninando approved these changes

2020-01-29 18:43 UTC, victorhmp approved these changes
Awesome! 👏

2020-01-29 19:19 UTC, merged