Implement cartChanged event
vtex-apps/minicart pull request #199
Opened 2020-01-08 18:21 UTC by klzns

#### What is the purpose of this pull request?

Add new event of cartChanged to be available to pixel apps.

#### What problem is this solving?

Listrak is a pixel app that needs to trigger an event with every item in the cart. Previously we only offered addToCart and removeFromCart, making it difficult for a pixel app to deal with this kind of event that needs the whole cart items.

#### How should this be manually tested?

With the new minicart
https://breno2--storecomponents.myvtex.com/

With the old minicart
https://breno--worldwidegolf.myvtex.com/

Check the events being printed in the console.

1. Add to cart from Shelf
2. Add to cart from search result
3. Add to cart from product page
4. Change quantity in minicart
5. Remove item from minicart

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-01-08 18:37 UTC, iaronaraujo approved these changes

2020-01-08 18:40 UTC, victorhmp approved these changes

2020-01-08 18:41 UTC, kaisermann approved these changes

2020-01-08 18:41 UTC, kaisermann commented on CHANGELOG.md
> +- New pixel event `cartChanged` when an item is removed or added
```suggestion
- New pixel event `cartChanged` when an item is removed or added.
```

2020-01-08 18:41 UTC, kaisermann commented on CHANGELOG.md
> +- New pixel event `cartChanged` when an item is removed or added
aprendi com o mestre da pontuação 
@salesfelipe

2020-01-08 18:43 UTC, emersonlaurentino approved these changes

2020-01-08 19:05 UTC, Klynger requested changes
If you add 3 items into the cart and then remove them the last item doesn't send any event

2020-01-09 16:44 UTC, Klynger approved these changes

2020-01-09 16:54 UTC, merged