Add new CSS handle for `minicart` block
vtex-apps/minicart pull request #203
Opened 2020-01-15 19:57 UTC by victorhmp

#### What is the purpose of this pull request?

Add a new `labelDiscountText` CSS handle.

#### What problem is this solving?

Solves this issue: https://app.clubhouse.io/vtex/story/29376/add-missing-css-handles-in-minicart

#### How should this be manually tested?

https://minicart--storecomponents.myvtex.com/

#### Screenshots or example usage

![Screen Shot 2020-01-15 at 16 57 20](https://user-images.githubusercontent.com/27777263/72466688-21df1680-37b8-11ea-995f-c99e5f129a5d.png)

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-01-15 20:26 UTC, Klynger approved these changes

2020-01-15 22:18 UTC, klzns approved these changes

2020-01-21 21:16 UTC, iaronaraujo requested changes
Please add a workspace with this linked on TBB and Boticario on the description of this PR!

2020-01-22 13:14 UTC, iaronaraujo approved these changes

2020-01-22 13:17 UTC, merged