Create new `content` block/interface
vtex-apps/minicart pull request #204
Opened 2020-01-16 02:54 UTC by victorhmp

#### What is the purpose of this pull request?

Create a new `content` block, which has `composition: "children"`.

#### What problem is this solving?

This should enable users to further customize the minicart.

#### How should this be manually tested?

Just add a few items to the minicart and see that there is a `rich-text` right above the `minicart-summary` block. This `rich-text` was placed there via `children`:

```json
"minicart.v2": {
    "children": ["minicart-base-content"]
  },
  "minicart-base-content": {
    "blocks": ["minicart-content", "minicart-empty-state"]
  },
  "minicart-content": {
    "children": [
      "minicart-product-list",
      "flex-layout.row#extension-point-demo",
      "minicart-summary"
    ]
  },

  "flex-layout.row#extension-point-demo": {
    "children": ["flex-layout.col#extension-point-demo"]
  },
  "flex-layout.col#extension-point-demo": {
    "children": ["rich-text#extension-point-demo"]
  },
  "rich-text#extension-point-demo": {
    "props": {
      "text": "This is a rich text passed as a child to minicart-content"
    }
  },
```

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-01-16 13:11 UTC, klzns approved these changes

2020-01-16 13:11 UTC, klzns commented on react/Summary.tsx
> +const CSS_HANDLES = ['minicartFooter'] as const
I think you can remove `minicartFooter` from the previous component

2020-01-16 13:18 UTC, klzns requested changes
Rebase and remove merge commit

2020-01-16 13:30 UTC, Klynger approved these changes

2020-01-22 13:16 UTC, closed without merging

2020-01-22 13:16 UTC, victorhmp commented
Closed this in favor of https://github.com/vtex-apps/minicart/pull/205