Update documentation
vtex-apps/minicart pull request #206
Opened 2020-01-24 17:42 UTC by victorhmp

#### What is the purpose of this pull request?

Add a new `Advanced Configuration` section to the documentation.

#### What problem is this solving?

This should help people to understand better how to customize `minicart.v2`

#### How should this be manually tested?

https://github.com/vtex-apps/minicart/tree/feature/advanced-docs/docs

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-01-27 14:48 UTC, denisebiscaro commented on docs/README.md
> +For further information on how to configure each of the blocks used to compose `minicar.v2`, check [VTEX Checkout Summary](https://vtex.io/docs/app/checkout-summary) and [VTEX Product List](https://v
`minicar.v2`-> `minicart.v2`

2020-01-28 16:00 UTC, guerreirobeatriz requested changes
Congratulations for your awesome job, Victor! 

My comments can be found below:

2020-01-28 16:00 UTC, guerreirobeatriz commented on docs/README.md
> +## Advanced Configuration
I believe this section should be in the Configuration section, such as: 

## Configuration 

pipipipopopo 

### Advanced configuration 

pipipipopopo. 

What do you think? Im saying that because once the configuration section teaches the user how to configure the Minicart, adding advanced configurations in it sounds reasonable to me.

2020-01-28 16:00 UTC, guerreirobeatriz commented on docs/README.md
> +## Advanced Configuration
I mean, the advanced config should be a h3 (### Advanced configuration)

2020-01-28 16:00 UTC, guerreirobeatriz commented on docs/README.md
> +The `minicart.v2` block is highly customizable because it has `composition: 'children'` and is composed of other blocks. Currently its default implementation is the following:
The `minicart.v2` block is highly customizable because it was built with the `composition: 'children'`. This means that according to its composition, it can be made up of other blocks. Currently, its default implementation is as follows:

2020-01-28 16:00 UTC, guerreirobeatriz commented on docs/README.md
> +This means that, when you use `minicart.v2` in your store, you're actually using this default implementation. So, to customize the blocks being used in your own implementation, you could get this def
By default implementation we mean that whenever you use `minicart.v2` in your store you're actually using the `json` above behind the scenes. 

Therefore, in order to customize the Minicart configuration, you can simply use the default implementation in your code and change it as you wish.

2020-01-28 16:00 UTC, guerreirobeatriz commented on docs/README.md
> +For further information on how to configure each of the blocks used to compose `minicart.v2`, check [VTEX Checkout Summary](https://vtex.io/docs/app/checkout-summary) and [VTEX Product List](https://
For further information on how to configure each of the blocks used to compose `minicart.v2`, check out [VTEX Checkout Summary](https://vtex.io/docs/app/checkout-summary) and [VTEX Product List](https://vtex.io/docs/product-list).

2020-01-28 17:53 UTC, victorhmp commented on docs/README.md
> +## Advanced Configuration
Sure! Makes sense! I thought about it, I added it as the last section assuming that most people would not be interested in it and would use the default implementation.
But I guess it does make more sense for it to be a subsection of `configuration`

2020-01-28 18:30 UTC, iaronaraujo approved these changes

2020-01-28 18:45 UTC, guerreirobeatriz approved these changes

2020-01-30 21:53 UTC, merged