Fix conditional rendering of children blocks
vtex-apps/minicart pull request #210
Opened 2020-01-30 19:33 UTC by victorhmp

#### What is the purpose of this pull request?

Fix the conditional logic being used to render children blocks.

#### What problem is this solving?

Components could be rendered more than once.

#### How should this be manually tested?

Using `blocks` only:

- [Madile Jeans](https://minicartfix--gc-jqu0734.myvtex.com/) (where the bug was spotted)

Using `blocks` + `children`:
- [Store Components](https://minicartdesigntweaks--storecomponents.myvtex.com/)

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-01-30 20:57 UTC, Klynger approved these changes

2020-01-31 17:04 UTC, iaronaraujo requested changes

2020-01-31 17:04 UTC, iaronaraujo commented on react/BaseContent.tsx
> +      <MinicartHeader minicarTitleHandle={handles.minicartTitle} />
```suggestion
      <MinicartHeader minicartTitleHandle={handles.minicartTitle} />
```

2020-01-31 17:15 UTC, iaronaraujo approved these changes

2020-01-31 17:17 UTC, merged