Clarify sentence regarding default implementation
vtex-apps/minicart pull request #212
Opened 2020-02-03 22:46 UTC by guerreirobeatriz

2020-02-04 14:38 UTC, klzns requested changes

2020-02-04 14:38 UTC, klzns commented on docs/README.md
> +Therefore, in order to customize the Minicart configuration, you can simply use the default implementation in your code instead of just declaring the `minicart` and change it as you wish.
```suggestion
Therefore, in order to customize the Minicart configuration, you can simply copy the code above and change it as you wish.
```

2020-02-04 14:53 UTC, klzns approved these changes

2020-02-04 18:40 UTC, victorhmp approved these changes

2020-04-28 18:29 UTC, Klynger approved these changes

2020-04-28 18:30 UTC, merged