Prop to always show quantity badge.
vtex-apps/minicart pull request #218
Opened 2020-03-05 13:48 UTC by lucaspacheco-acct

#### What is the purpose of this pull request?
Add `alwaysShowQuantityBadge` prop to minicart.v2 to show the quantity badge even when the amount of products in cart is zero.

#### What problem is this solving?
When there's no product in cart the quantity badge on minicart.v2 is not shown, the `alwaysShowQuantityBadge` allows to configure if the badge should appears when the amount of products in cart is zero.

#### How should this be manually tested?
Add the prop to the minicart.v2 block.
Workspace for tests: https://minicartbadge--acctglobal.myvtex.com/

#### Screenshots or example usage
Example in blocks: https://i.imgur.com/yzDmoS6.png
How it should looks when cart is empty: https://i.imgur.com/3ukLbyi.png

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-03-05 15:09 UTC, klzns requested changes
Thank you for this pull request! It looks really good.

One thing that would make it better is to change the API. Can you change the prop to be named `quantityDisplay` with the possible values: `always`, `never`, and `not-empty`?

We learnt that boolean props doesnt scale well, that's why we are now preferring to use enum props instead.

2020-03-05 20:30 UTC, lucaspacheco-acct commented
@klzns I've changed the props to receive Enum values. I've considered like was done in `search-result`.

2020-03-09 18:51 UTC, klzns approved these changes

2020-03-09 18:57 UTC, victorhmp approved these changes

2020-03-09 18:58 UTC, victorhmp commented
Thanks for the contribution @lucaspacheco-acct ! Awesome work! 😄

2020-03-11 14:57 UTC, guerreirobeatriz approved these changes

2020-03-11 16:58 UTC, merged

2020-03-11 16:59 UTC, klzns commented
@allcontributors add @lucaspacheco-acct for code