Add prop to initialOpen option
vtex-apps/minicart pull request #223
Opened 2020-04-03 02:20 UTC by ygorneves10

#### What is the purpose of this pull request?

Allow to start open the component

#### What problem is this solving?

The customer needs the Mini Cart to start open. I created a PR in the Drawer repository with this prop too.

#### How should this be manually tested?
https://minicartopen--aldi.myvtex.com/

#### Screenshots or example usage

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2020-04-03 02:21 UTC, ygorneves10 commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [ ]  Patch
> * [x]  Minor
> * [ ]  Major
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2020-04-08 17:11 UTC, guerreirobeatriz requested changes
Thank you!

2020-04-08 17:11 UTC, guerreirobeatriz commented on docs/README.md
> +| `initialOpen`          | `Boolean`  | Minicart starts open.                                                                                   | `false`         |
```suggestion
| `initialOpen`          | `Boolean`  | Whether the Minicart will be displayed already opened (`true`) or not (`false`).            | `false`         |
```

2020-04-09 16:38 UTC, klzns requested changes
The bot will automatically change the version

2020-04-09 16:38 UTC, klzns commented on manifest.json
> +  "version": "2.44.0",
```suggestion
  "version": "2.43.5",
```

2020-04-09 16:38 UTC, klzns commented on CHANGELOG.md
> +## [2.44.0] - 2020-04-03
```suggestion
```

2020-04-09 16:51 UTC, klzns requested changes
I rebased your branch with the current master.

I've tried using this feature but it didnt work. Can you provide a workspace with this linked, please? Thanks

2020-04-28 18:34 UTC, Klynger commented
Closing this PR due to inactivity

2020-04-28 18:34 UTC, closed without merging