Update the pop-up to appear when the mini cart button is clicked
vtex-apps/minicart pull request #23
Opened 2018-07-10 15:01 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Update the pop-up to appear when the mini cart button is clicked instead of on hover.

#### What problem is this solving?
The pop-up was appearing when the mini cart button was on hover.

#### How should this be manually tested?
https://waza--storecomponents.myvtex.com/

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-07-10 15:09 UTC, brunojdo approved these changes

2018-07-10 20:27 UTC, claudivanfilho commented
O minicart está acima do account!

![screenshot from 2018-07-10 17-24-32](https://user-images.githubusercontent.com/4960686/42535663-56e18a22-8466-11e8-87a7-b38f9cc84657.png)

2018-07-10 20:28 UTC, claudivanfilho requested changes
Olha meu comentário

2018-07-11 13:50 UTC, claudivanfilho approved these changes

2018-07-11 13:54 UTC, merged