Feature/pass payment data to summary
vtex-apps/minicart pull request #268
Opened 2021-03-31 13:30 UTC by Jeffersonacct

#### What problem is this solving?

Passing paymentData as prop to Summary component to allow showing installments related information inside checkout-summary app.

#### How to test it?

Go to [Workspace](https://addnewblockcheckoutsummary--tokstokio.myvtex.com/) add a product to cart and hover over minicart icon. Inspect SummaryContextProvider element with React DevTools to confirm paymentData being passed as prop.

#### Screenshots or example usage:

![image](https://user-images.githubusercontent.com/81425175/113151901-f1906600-920b-11eb-95a4-5c2bb716b42c.png)

2021-05-24 18:58 UTC, victorhmp commented on CHANGELOG.md
```suggestion
```

Removing this line should resolve the conflict being pointed out by GitHub ;)

2021-05-24 19:01 UTC, victorhmp requested changes
Hi @Jeffersonacct!
Thanks for the PR! The code LGTM, but I couldn't test it in your workspace. Could you please update the workspace or provide a new one?

2021-05-25 22:24 UTC, icazevedo approved these changes

2021-06-21 18:57 UTC, victorhmp approved these changes

2021-06-29 18:15 UTC, merged