Feature/summary-installments block
vtex-apps/minicart pull request #281
Opened 2021-06-23 12:13 UTC by JonathanLacerda

#### What problem is this solving?

Passing paymentData as prop to Summary component to allow showing installments related information inside checkout-summary app.

#### How to test it?

Go to [Workspace](https://installmentsminicart--tokstokio.myvtex.com/), add a product to cart and hover over minicart icon. Inspect SummaryContextProvider element with React DevTools to confirm paymentData being passed as prop.

#### Screenshots or example usage:

![](https://user-images.githubusercontent.com/34974565/100485803-3d0cf900-30e0-11eb-99f7-21968780848a.png)

2021-07-12 12:38 UTC, igorbrasileiro requested changes
What's the purpose of this PR?

2021-07-12 12:38 UTC, igorbrasileiro commented on react/Summary.tsx
> +    orderForm: { totalizers, value, paymentData},
Fix this lint issue.
```suggestion
    orderForm: { totalizers, value, paymentData },
```

2021-07-13 11:30 UTC, JonathanLacerda commented
> What's the purpose of this PR?

The purpose of this PR is to pass payment data related to payment in installments for displaying this information on screen.
I have another PR that will show this data on screen (https://github.com/vtex-apps/checkout-summary/pull/60)

2021-07-13 11:31 UTC, JonathanLacerda reviewed
Resolvindo fix insue

2021-07-13 13:32 UTC, igorbrasileiro commented
> The purpose of this PR is to pass payment data related to payment in installments for displaying this information on screen.
> I have another PR that will show this data on screen ([vtex-apps/checkout-summary#60](https://github.com/vtex-apps/checkout-summary/pull/60))

But you are only adding the changelog. The payment data already exists.

2021-08-12 19:58 UTC, JonathanLacerda commented
> > The purpose of this PR is to pass payment data related to payment in installments for displaying this information on screen.
> > I have another PR that will show this data on screen ([vtex-apps/checkout-summary#60](https://github.com/vtex-apps/checkout-summary/pull/60))
> 
> But you are only adding the changelog. The payment data already exists.

Yes, we need this payment data,
Is relative with this PR https://github.com/vtex-apps/checkout-summary/pull/60

2021-08-16 19:10 UTC, victorhmp commented
@JonathanLacerda Wait, this PR can be closed, right? The only file that's being changed is the CHANGELOG.md file.
I'm looking at the checkout-summary PR right now, but I don't see how this PR is necessary 😅  Maybe you forgot to push something?

2021-08-18 19:08 UTC, JonathanLacerda commented
> @JonathanLacerda Wait, this PR can be closed, right? The only file that's being changed is the CHANGELOG.md file.
> I'm looking at the checkout-summary PR right now, but I don't see how this PR is necessary  Maybe you forgot to push something?

Hi @victorhmp, I just made small changes to the "react/Summary.tsx" file, it's here https://github.com/vtex-apps/minicart/pull/281/commits/ad21efe846e1785e4da5c4c8a8afa2c206d30cc6
Can't visualize it?

2022-09-02 09:18 UTC, closed without merging