Add content loader into minicart item's image
vtex-apps/minicart pull request #30
Opened 2018-08-08 18:57 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Add content loader into minicart item's image.

#### How should this be manually tested?
https://waza--storecomponents.myvtex.com/

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-08-08 20:43 UTC, gugabribeiro requested changes

2018-08-08 20:43 UTC, gugabribeiro commented on react/components/Image.js
> +    const { imageUrl, alt } = this.props
Try to choose one of the patterns, `imageUrl` and `imageAlt` or `url` and `alt`

2018-08-08 20:46 UTC, andreldsa approved these changes

2018-08-08 21:00 UTC, gugabribeiro approved these changes

2018-08-08 21:19 UTC, estacioneto requested changes

2018-08-08 21:19 UTC, estacioneto commented on react/components/Image.js
> +      <rect x="0" y="0" rx="5" ry="5" width="500" height="500" />
Put classnames so it can be editable via CSS

2018-08-09 16:50 UTC, estacioneto approved these changes

2018-08-09 16:51 UTC, merged