feat(accessibility): aria properties added to resolve accessibility a…
vtex-apps/minicart pull request #331
Opened 2023-10-09 14:37 UTC by joaocongio

#### What problem is this solving?

Adicionado propriedades ARIA para resolver ajustes apontados pelo Lighthouse.
ButtonWithIcon atualmente não aceita a propriedade aria-label. Foi feito um ajuste também no app vtex.styleguide para aceitar essa propriedade.
PR Styleguide: https://github.com/vtex/styleguide/pull/1447

#### How to test it?

[Workspace](https://www.samsclub.com.br/?workspace=testeacessibilidade)

Executar o teste no Lighthouse ou Pagespeed.

#### Screenshots or example usage:

![Minicart After](https://github.com/vtex-apps/minicart/assets/22462037/d7dff1ba-ee99-474d-b028-be85cd162c64)

![minicart before](https://github.com/vtex-apps/minicart/assets/22462037/5f4f810c-f929-4837-85ad-03edd258d885)

2023-10-09 14:38 UTC, joaocongio commented
> Hi! I'm VTEX IO CI/CD Bot and I'll be helping you to publish your app! 🤖
> 
> Please select which version do you want to release:
> 
> * [x]  Patch (backwards-compatible bug fixes)
> * [ ]  Minor (backwards-compatible functionality)
> * [ ]  Major (incompatible API changes)
> 
> And then you just need to merge your PR when you are ready! There is **no need** to create a release commit/tag.
> 
> * [ ]  No thanks, I would rather do it manually 😞

2023-11-07 17:54 UTC, filipewl requested changes
Boa @joaocongio! Deixei alguns comentários pra gente discutir juntos. Eu tenho a impressão que conseguimos resolver os alertas sem [essas modificações feitas no styleguide](https://github.com/vtex/styleguide/pull/1447/files). Vale tentar.

2023-11-07 17:54 UTC, filipewl commented on react/Minicart.tsx
> +              aria-label="Minicart"
Você tem certeza que esse valor está sendo usado? Olhando o componente do `DrawerMode` eu não vejo como ele usando esses valores. No [workspace de teste](https://www.samsclub.com.br/?workspace=testeacessibilidade) eu inspecionei o HTML e também não consegui achar nenhum elemento com esse atributo específico.

2023-11-07 17:54 UTC, filipewl commented on react/components/MinicartIconButton.tsx
> +      id="miniCartButton"
Sugiro remover esse `id` já que contribui pra resolução do problema proposto.
```suggestion
```

2023-11-07 17:54 UTC, filipewl commented on react/components/MinicartIconButton.tsx
> +      ariaLabel="Open Minicart"
Entendi que passar essa prop seria permitida com [essas outras modificações propostas](https://github.com/vtex/styleguide/pull/1447/files). Porém, acredito que podemos resolver o problem inicial, do alerta de acessibilidade que [botões precisam ter um nome acessível](https://dequeuniversity.com/rules/axe/4.8/button-name), sem precisar das modificações no repositório do styleguide!

Entendo que você estava tentando passar uma `aria-label` pro botão com ícone do carrinho, para que ele tivesse um nome acessível. De fato, atualmente ele não tem nenhum nome acessível:
![CleanShot 2023-11-07 at 14 40 05](https://github.com/vtex-apps/minicart/assets/381395/ef8ae34b-ef77-4675-957a-d85e526ab23d)

Mas podemos dar um nome pra ele, sem precisar passar o `aria-label` pra ele diretamente, e sim adicionar um aria-label no elemento do ícone passado pela prop `icon`, e.g.:

https://github.com/vtex-apps/minicart/blob/1b05d5d275e8f8c91c23e6e1d51a7f6ae87f2e9c/react/components/MinicartIconButton.tsx#L103-L104

Com esse modificação aqui mesmo neste arquivo, o botão vai automaticamente herdar o nome que precisa ter:
![CleanShot 2023-11-07 at 14 41 26](https://github.com/vtex-apps/minicart/assets/381395/33bd1ec3-9e15-4e86-b1cf-e6a18cc1b08b)

Faz sentido pra você? Com isso não precisaríamos [dessa mudança](https://github.com/vtex/styleguide/pull/1447/files).

Aqui só teríamos que usar [aquela funcionalidade de internacionalizar o conteúdo](https://github.com/vtex-apps/store-components/pull/1096#discussion_r1378269632) do `aria-label` que indica a ação de abrir o carrinho.

2023-11-08 18:10 UTC, joaocongio commented on react/Minicart.tsx
> +              aria-label="Minicart"
Não me lembro exatamente o motivo que eu coloquei esse aria-label.
Vamos considerar que não é necessário no momento.

2023-11-08 18:10 UTC, joaocongio commented on react/components/MinicartIconButton.tsx
> +      id="miniCartButton"
Removido.

2023-11-08 18:32 UTC, joaocongio commented on react/components/MinicartIconButton.tsx
> +      ariaLabel="Open Minicart"
Fiz as alterações usando a sua sugestão e também foi preciso adicionar a propriedade role="img", pois passou a acusar um novo erro.
![image](https://github.com/vtex-apps/minicart/assets/22462037/4c4b9524-09d5-442d-ba4c-0c0988a94532)

2024-01-04 12:30 UTC, gvc approved these changes

2024-01-30 17:52 UTC, joaocongio commented
@gvc tem alguma previsão de deploy para esse ajuste? Obrigado.

2024-06-25 18:05 UTC, joaocore commented
@gvc @filipewl esse ajuste ainda será feito deploy?

2024-08-26 17:35 UTC, closed without merging