Fix box position to be compatible with the new header design
vtex-apps/minicart pull request #35
Opened 2018-08-17 14:00 UTC by salesfelipe

#### What is the purpose of this pull request?
Fix box position to be compatible with the new header design

#### What problem is this solving?
Compatibility with the new header design

#### How should this be manually tested?
[workspace](https://felipeoficial--storecomponents.myvtex.com)

#### Screenshots or example usage
![image](https://user-images.githubusercontent.com/3926634/44270060-b680c600-a20c-11e8-8d17-f2a451839d94.png)

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-08-17 16:18 UTC, andreldsa approved these changes

2018-08-17 18:51 UTC, vitoria requested changes

2018-08-17 18:51 UTC, vitoriaHeliane commented on react/global.css
> +  right: 6.7rem;
Eu acho que a melhor solução seria colocar o popup em position absolute em relação ao ícone que deveria estar com position relative.

2018-08-17 19:49 UTC, vitoria requested changes
A label do minicart ficou desalinhada.
![captura de tela de 2018-08-17 16-48-29](https://user-images.githubusercontent.com/12852518/44285951-aaf9c300-a23d-11e8-8327-1d5e5ec8dbca.png)

2018-08-20 12:07 UTC, claudivanfilho approved these changes

2018-08-20 19:44 UTC, vitoria approved these changes

2018-08-21 13:15 UTC, merged