Update the Quantity Selector UI and Fix change quantity
vtex-apps/minicart pull request #37
Opened 2018-08-23 11:58 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Update the quantity selector UI and Fix change quantity

#### What problem is this solving?
The Mini Cart Item wasn't using the Style guide's Numeric Stepper and there was an error when changing the item quantity.

#### How should this be manually tested?
https://waza--storecomponents.myvtex.com/admin/cms/storefront

#### Screenshots or example usage
![captura de tela de 2018-08-22 15-23-01](https://user-images.githubusercontent.com/12852518/44524110-a5bfcc80-a6b2-11e8-9985-c97010eff415.png)

#### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-08-23 13:06 UTC, claudivanfilho requested changes

2018-08-23 13:06 UTC, claudivanfilho commented on react/components/MiniCartContent.js
> +  getNoRepetedItems = () =>
I think that `getDistinctItems` or `getGroupedItems` is a better name to this function

2018-08-23 13:06 UTC, ClaudivanFilho commented on react/components/MiniCartContent.js
> +      const updatedItem = [itemsPayload[0]].map(item => {
there is no need of this array here

2018-08-23 13:06 UTC, ClaudivanFilho commented on react/components/MiniCartContent.js
> +      let updatedItem = [itemsPayload[0]].map(item => {
same here

2018-08-23 13:06 UTC, ClaudivanFilho commented on react/components/MiniCartContent.js
> +      updatedItem = [itemsPayload[1]].map(item => {
same here

2018-08-23 13:06 UTC, ClaudivanFilho commented on react/components/MiniCartContent.js
> +    const index = orderForm.items.indexOf(itemsPayload[0])
use `head` of ramda.

U r using `itemsPayload[0]` many times in the code, better to assign to a variable.

2018-08-27 16:25 UTC, salesfelipe approved these changes

2018-08-29 16:32 UTC, claudivanfilho requested changes

2018-08-29 16:32 UTC, ClaudivanFilho commented on react/global.css
> +  width: 65px;
use w3 of tachyons

2018-08-29 16:32 UTC, ClaudivanFilho commented on react/global.css
> +  height: 65px;
use h3 of tachyons

2018-08-29 16:32 UTC, ClaudivanFilho commented on react/global.css
> +  height: 34px;
use h2 of tachyons

2018-08-29 16:32 UTC, ClaudivanFilho commented on react/global.css
> +  max-width: 100%;
use `.mw-100` of tachyons

2018-08-29 16:32 UTC, ClaudivanFilho commented on react/global.css
> +  white-space: nowrap;
use `truncate` of tachyons

2018-08-29 16:32 UTC, ClaudivanFilho commented on react/global.css
>    white-space: nowrap;
Same here

2018-08-29 16:57 UTC, claudivanfilho approved these changes

2018-08-30 13:26 UTC, andreldsa approved these changes

2018-08-30 13:38 UTC, merged