Change sidebar header UI
vtex-apps/minicart pull request #39
Opened 2018-08-30 13:48 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Change sidebar header according to the new store design.

#### How should this be manually tested?
[Click here to access the workspace](https://waza2--storecomponents.myvtex.com/)

#### Screenshots or example usage
![captura de tela de 2018-08-30 10-46-06](https://user-images.githubusercontent.com/12852518/44855705-0c5c6180-ac42-11e8-8873-4515f7c600ad.png)

#### Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-08-30 14:01 UTC, gugabribeiro approved these changes

2018-08-30 18:50 UTC, salesfelipe approved these changes

2018-08-30 18:52 UTC, andreldsa approved these changes

2018-08-31 10:48 UTC, brunojdo requested changes

2018-08-31 10:48 UTC, brunojdo commented on react/MiniCart.js
> +              style={{ color: labelColor }}
Why? :(

2018-08-31 14:51 UTC, brunojdo approved these changes

2018-08-31 14:51 UTC, merged