Use filled icons from styleguide instead local icons
vtex-apps/minicart pull request #53
Opened 2018-11-19 13:07 UTC by ArthurSampaio

#### What is the purpose of this pull request?

By design requirement it is necessary to use filled icons instead of the outline icons.

#### What problem is this solving?

Using icons from `vtex.styleguide`

#### How should this be manually tested?
https://filled--storecomponents.myvtex.com/

#### Screenshots or example usage
![frame_2](https://user-images.githubusercontent.com/17649410/48708701-042d1600-ebe2-11e8-9220-caf34f3b4a1f.png)

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-11-19 13:22 UTC, rerissondaniel approved these changes

2018-11-19 14:53 UTC, vitoria approved these changes

2018-11-19 17:51 UTC, brunojdo reviewed
use IconPack of dreamstore. cc @lucasecdb @matheusps

2018-11-19 17:52 UTC, brunojdo requested changes
use IconPack of dreamstore. cc @lucasecdb @matheusps

2018-11-19 18:12 UTC, lucis approved these changes

2018-11-21 19:13 UTC, brunojdo approved these changes

2018-11-21 19:16 UTC, merged