Fix minicart design and items sort
vtex-apps/minicart pull request #62
Opened 2018-12-10 18:59 UTC by ArthurSampaio

#### What is the purpose of this pull request?

Fix small bugs that appeared in the last release like layout content. 

#### What problem is this solving?

#### How should this be manually tested?
https://fixminicart--storecomponents.myvtex.com/

#### Screenshots or example usage
**Before:** 
_[Pixel]_
![minicartbefore](https://user-images.githubusercontent.com/17649410/49753742-06d7d400-fc93-11e8-8c23-1b8fc8da682a.PNG) 
_[Iphone5]_
![minicartebeforeiphone](https://user-images.githubusercontent.com/17649410/49753750-0b9c8800-fc93-11e8-8da9-b11aaad531c1.PNG)

**After:**
_[Pixel]_
![minicarteafterpixel](https://user-images.githubusercontent.com/17649410/49753792-2c64dd80-fc93-11e8-9311-ffb48c7d2a3e.PNG)
_[Iphone5]_
![minicartafter](https://user-images.githubusercontent.com/17649410/49753802-338beb80-fc93-11e8-8d56-1ade836f5fa1.PNG)

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-12-10 19:46 UTC, brunojdo approved these changes

2018-12-12 15:15 UTC, rerissondaniel approved these changes

2018-12-12 17:41 UTC, brunojdo requested changes
Adjust with CSS modules feature

2018-12-12 18:33 UTC, brunojdo approved these changes

2018-12-12 18:36 UTC, merged