Update the CSS module classes' name to be in CamelCase
vtex-apps/minicart pull request #64
Opened 2018-12-13 18:51 UTC by vitoriaHeliane

#### What is the purpose of this pull request?
Update the CSS module classes' name to be in CamelCase.

#### What problem is this solving?
The classes' name was not following a pattern.

#### How should this be manually tested?
[Click here to access the workspace.](https://waza--storecomponents.myvtex.com/)

#### Types of changes
- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2018-12-13 18:52 UTC, theomoura approved these changes

2018-12-13 18:55 UTC, ArthurSampaio approved these changes

2018-12-13 19:09 UTC, lucis requested changes

2018-12-13 19:09 UTC, luciannojunior commented on react/minicart.css
> +.itemImageLoader {
Was it being used somewhere?

2018-12-14 14:14 UTC, Klynger approved these changes

2018-12-14 14:18 UTC, JuanAlmeida12 approved these changes

2018-12-14 14:35 UTC, lucis approved these changes

2018-12-14 20:33 UTC, merged