Fix/price overlapping mobile
vtex-apps/minicart pull request #77
Opened 2019-01-11 19:57 UTC by paul0vinicius

#### What is the purpose of this pull request?
When 5 or more products are added to the minicart, the products push down the prices overlapping the checkout button. This pr aims to solve this overlapping by changing the max-height of the minicart content.

#### What problem is this solving?
The overlapping of the total price in the minicart in the mobile view.

#### How should this be manually tested?
Using chrome (mobile view) for any resolution you must add 5 or more products into the minicart and then open it. You will see the overlapping in the total price and the saved money.

This is the [Fixed Version](https://fixpriceoverlapping--storecomponents.myvtex.com/).

#### Screenshots or example usage
![bug-overlapping](https://user-images.githubusercontent.com/9946330/51056420-8a058600-15c1-11e9-865e-742167a84721.png)

#### Types of changes
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2019-01-11 20:00 UTC, theomoura requested changes
Edit the Changelog.md

2019-01-11 20:00 UTC, theomoura commented on react/minicart.css
> +.contentPrice {
Are you really using the contentPrice token? If not, remove it

2019-01-11 20:08 UTC, Klynger approved these changes

2019-01-13 17:04 UTC, ArthurSampaio reviewed
Lack update the changelog. :hammer:

2019-01-14 11:26 UTC, brunojdo approved these changes

2019-01-14 11:28 UTC, paul0vinicius commented on react/minicart.css
> +.contentPrice {
It will be removed after the new changes

2019-01-14 11:42 UTC, theomoura approved these changes

2019-01-14 12:11 UTC, oldufre requested changes
Paulo, ficou bom,  resolveu aquele problema, mas mudou outros paddings do minicart =/
Queria que tu colocasse na parte superior e na inferior um padding de 1 rem e entre eles um de 0.5 rem

2019-01-14 19:37 UTC, oldufre approved these changes

2019-01-15 12:33 UTC, merged