Make icon receive it's properties correctly.
vtex-apps/minicart pull request #83
Opened 2019-01-22 16:08 UTC by matheusps

#### What is the purpose of this pull request? | What problem is this solving?
As the title says.

#### How should this be manually tested?
This [workspace](https://restyleheadermobile--storecomponents.myvtex.com) on mobile mode.

#### Types of changes
- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Requires change to documentation, which has been updated accordingly.

2019-01-22 16:16 UTC, Klynger approved these changes

2019-01-22 17:36 UTC, JuanAlmeida12 approved these changes

2019-01-22 18:32 UTC, theomoura approved these changes

2019-01-26 22:43 UTC, brunojdo requested changes
The icon needs to get the current color of the div that encapsulates him.

2019-03-07 18:50 UTC, closed without merging